[package]
name = "token_calculator"
version = "0.3.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }

[[bin]]
name = "calculator"
path = "src/main.rs"
